<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/bloggie/app/modules/default/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-01-30T06:02:41+0000

return array (
  'BlogDefaultBaseAction' => 'C:\\workspace\\bloggie\\app/modules/Default/lib/action/BlogDefaultBaseAction.class.php',
  'BlogDefaultBaseModel' => 'C:\\workspace\\bloggie\\app/modules/Default/lib/model/BlogDefaultBaseModel.class.php',
  'BlogDefaultBaseView' => 'C:\\workspace\\bloggie\\app/modules/Default/lib/view/BlogDefaultBaseView.class.php',
);

?>