<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/bloggie/app/modules/Widgets/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-01-30T06:02:41+0000

return array (
  'BlogWidgetsBaseAction' => 'C:\\workspace\\bloggie\\app/modules/Widgets/lib/action/BlogWidgetsBaseAction.class.php',
  'BlogWidgetsBaseModel' => 'C:\\workspace\\bloggie\\app/modules/Widgets/lib/model/BlogWidgetsBaseModel.class.php',
  'BlogWidgetsBaseView' => 'C:\\workspace\\bloggie\\app/modules/Widgets/lib/view/BlogWidgetsBaseView.class.php',
);

?>