<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/bloggie/app/modules/default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-01-30T06:02:41+0000

return array (
)

?>