<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/bloggie/app/modules/Widgets/validate/Content.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2013-01-30T06:02:41+0000



?>