<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/bloggie/app/config/databases.xml
// Generated by: AgaviDatabaseConfigHandler
// Date: 2013-01-30T06:02:41+0000

$database = new AgaviPropelDatabase();
$this->databases['propelom'] = $database;
$database->initialize($this, array (
  'config' => 'C:\\workspace\\bloggie\\app/config/bloggie-conf.php',
));
$this->defaultDatabaseName = 'propelom';

?>