<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/bloggie/app/config/settings.xml
// Generated by: AgaviSettingConfigHandler
// Date: 2013-01-30T06:02:41+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'Default',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'Default',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'Default',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'Default',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'Default',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'Default',
  'actions.login_action' => 'Login',
  'core.app_name' => 'Bloggie',
  'core.available' => true,
  'core.debug' => true,
  'core.use_database' => true,
  'core.use_logging' => true,
  'core.use_security' => true,
  'core.use_translation' => true,
  'exception.default_template' => 'C:\\workspace\\bloggie\\libs\\agavi/exception/templates/shiny.php',
  'exception.templates.console' => 'C:\\workspace\\bloggie\\libs\\agavi/exception/templates/plaintext.php',
));

?>